import { createHmac, randomUUID, timingSafeEqual, publicEncrypt, constants } from 'node:crypto';
export type PaymentMethod='MANUAL'|'MPESA'|'EMOLA'|'MOCK';
export type ProviderStatus='PENDING'|'PROCESSING'|'PAID'|'FAILED'|'CANCELLED'|'REFUNDED'|'EXPIRED';
export type ChargeInput={amount:string;currency:string;phone:string;reference:string;idempotencyKey:string;method:PaymentMethod};
export type ChargeResult={providerReference:string;status:ProviderStatus;raw:unknown};
export type ProviderConfig={provider?:string;baseUrl?:string;token?:string;walletId?:string;webhookSecret?:string};
export interface PaymentProvider{name:string;createCharge(input:ChargeInput):Promise<ChargeResult>;query?(providerReference:string):Promise<ChargeResult>;refund?(providerReference:string,amount:string):Promise<ChargeResult>}
const digits=(v:string)=>v.replace(/\D/g,''); const localPhone=(v:string)=>digits(v).replace(/^258/,''); const intlPhone=(v:string)=>digits(v).startsWith('258')?digits(v):`258${digits(v)}`;
export function mapStatus(value:unknown):ProviderStatus{const s=String(value||'').toLowerCase();if(['paid','success','successful','completed','confirmed'].includes(s))return'PAID';if(['failed','error','declined'].includes(s))return'FAILED';if(['cancelled','canceled'].includes(s))return'CANCELLED';if(['refunded','reversed'].includes(s))return'REFUNDED';if(s==='expired')return'EXPIRED';if(['processing','initiated'].includes(s))return'PROCESSING';return'PENDING'}
class MockProvider implements PaymentProvider{name='mock';async createCharge(i:ChargeInput){const paid=process.env.MOCK_PAYMENT_AUTO_SUCCESS==='true';return{providerReference:`mock_${randomUUID()}`,status:(paid?'PAID':'PROCESSING') as ProviderStatus,raw:{sandbox:true,method:i.method}}}}
class PagarProvider implements PaymentProvider{name='pagar';private base=process.env.PAYMENT_API_BASE_URL||'https://api.pagar.co.mz';private key=process.env.PAYMENT_API_KEY||'';private async request(path:string,init:RequestInit){if(!this.key)throw new Error('PAYMENT_PROVIDER_NOT_CONFIGURED');const r=await fetch(`${this.base.replace(/\/$/,'')}${path}`,{...init,headers:{authorization:`Bearer ${this.key}`,'content-type':'application/json',accept:'application/json',...(init.headers||{})},signal:AbortSignal.timeout(15000)});const d:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||`PAYMENT_HTTP_${r.status}`);return d}async createCharge(i:ChargeInput){const raw:any=await this.request(process.env.PAYMENT_CREATE_PATH||'/api/v1/payments',{method:'POST',headers:{'idempotency-key':i.idempotencyKey},body:JSON.stringify({amount:Number(i.amount),currency:i.currency==='MT'?'MZN':i.currency,payment_method:i.method.toLowerCase(),phone:localPhone(i.phone),reference:i.reference})});return{providerReference:String(raw.id||raw.transaction_id||raw.reference||i.reference),status:mapStatus(raw.status),raw}}async query(providerReference:string){const raw:any=await this.request(`${process.env.PAYMENT_STATUS_PATH||'/api/v1/payments/'}${encodeURIComponent(providerReference)}`,{method:'GET'});return{providerReference,status:mapStatus(raw.status),raw}}}
class ClicPayProvider implements PaymentProvider{name='clicpay';private base:string;private token:string;private wallet:string;constructor(cfg:ProviderConfig={}){this.base=(cfg.baseUrl||process.env.CLICPAY_BASE_URL||'https://clicpay.co.mz').replace(/\/$/,'');this.token=cfg.token||process.env.CLICPAY_TOKEN||'';this.wallet=cfg.walletId||process.env.CLICPAY_WALLET_ID||'';}async createCharge(i:ChargeInput){if(!this.token||!this.wallet)throw new Error('PAYMENT_PROVIDER_NOT_CONFIGURED');if(!['MPESA','EMOLA'].includes(i.method))throw new Error('PAYMENT_METHOD_UNSUPPORTED');const r=await fetch(`${this.base}/api/v2/wallets/${encodeURIComponent(this.wallet)}/c2b/${i.method.toLowerCase()}`,{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${this.token}`,'Content-Type':'application/json',Accept:'application/json','Idempotency-Key':i.idempotencyKey},body:JSON.stringify({msisdn:localPhone(i.phone),amount:Number(i.amount),reference_description:`Atelier ${i.reference}`.slice(0,32),internal_notes:`Pedido ${i.reference}`})});const raw:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(raw?.message||`PAYMENT_HTTP_${r.status}`);return{providerReference:String(raw.clicpay_reference||raw.reference||i.reference),status:mapStatus(raw.status),raw}}async query(providerReference:string){if(!this.token)return Promise.reject(new Error('PAYMENT_PROVIDER_NOT_CONFIGURED'));const r=await fetch(`${this.base}/api/v2/transactions/${encodeURIComponent(providerReference)}/status`,{method:'GET',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${this.token}`,Accept:'application/json'}});const raw:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(raw?.message||`PAYMENT_HTTP_${r.status}`);return{providerReference,status:mapStatus(raw.status),raw}}}
class MpesaProvider implements PaymentProvider{name='mpesa';private base=(process.env.MPESA_BASE_URL||'https://api.sandbox.vm.co.mz:18352').replace(/\/$/,'');private auth(){const api=process.env.MPESA_API_KEY||'',pub=(process.env.MPESA_PUBLIC_KEY||'').replace(/\\n/g,'\n');if(!api||!pub)throw new Error('PAYMENT_PROVIDER_NOT_CONFIGURED');return publicEncrypt({key:pub,padding:constants.RSA_PKCS1_PADDING},Buffer.from(api)).toString('base64')}async createCharge(i:ChargeInput){if(i.method!=='MPESA')throw new Error('PAYMENT_METHOD_UNSUPPORTED');if(i.currency!=='MT')throw new Error('MPESA_REQUIRES_MT');const sp=process.env.MPESA_SERVICE_PROVIDER_CODE||'';if(!sp)throw new Error('PAYMENT_PROVIDER_NOT_CONFIGURED');const r=await fetch(`${this.base}/ipg/v1x/c2bPayment/singleStage/`,{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${this.auth()}`,'Content-Type':'application/json',Origin:'developer.mpesa.vm.co.mz'},body:JSON.stringify({input_TransactionReference:i.reference.slice(-20),input_CustomerMSISDN:intlPhone(i.phone),input_Amount:Number(i.amount).toFixed(2),input_ThirdPartyReference:i.reference.replace(/[^A-Za-z0-9]/g,'').slice(-20),input_ServiceProviderCode:sp})});const raw:any=await r.json().catch(()=>({}));const ok=r.ok&&raw.output_ResponseCode==='INS-0';return{providerReference:String(raw.output_ConversationID||raw.output_TransactionID||i.reference),status:(ok?'PAID':'FAILED') as ProviderStatus,raw}}}
export function getPaymentProvider(config:ProviderConfig={}):PaymentProvider{const n=(config.provider||process.env.PAYMENT_PROVIDER||'mock').toLowerCase();if(n==='pagar')return new PagarProvider();if(n==='clicpay')return new ClicPayProvider(config);if(n==='mpesa')return new MpesaProvider();return new MockProvider()}
export function verifyWebhook(raw:string,signature:string|undefined,secretOverride?:string){const secret=secretOverride||process.env.PAYMENT_WEBHOOK_SECRET||'';if(!secret||!signature)return false;const expected=createHmac('sha256',secret).update(raw).digest('hex'),supplied=signature.replace(/^sha256=/,'');try{return expected.length===supplied.length&&timingSafeEqual(Buffer.from(expected),Buffer.from(supplied))}catch{return false}}
